language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git"
    - TESTS=false
    - PINS="lwt.dev:https://github.com/mirage/lwt.git#tracing mirage-profile:https://github.com/mirage/mirage-profile.git"
    - WITH_TRACING=1
  matrix:
    - OCAML_VERSION=4.03 POST_INSTALL_HOOK="make MODE=unix && make testrun SUDO=sudo && make clean"
    - OCAML_VERSION=4.03 UPDATE_GCC_BINUTILS=1 POST_INSTALL_HOOK="make MODE=xen  && make clean"
    - OCAML_VERSION=4.03 UPDATE_GCC_BINUTILS=1 POST_INSTALL_HOOK="make MODE=ukvm  && make clean"
    - OCAML_VERSION=4.03 UPDATE_GCC_BINUTILS=1 POST_INSTALL_HOOK="make MODE=virtio  && make clean"
    - OCAML_VERSION=4.02 POST_INSTALL_HOOK="make MODE=unix && make testrun SUDO=sudo && make clean"
    - OCAML_VERSION=4.02 UPDATE_GCC_BINUTILS=1 POST_INSTALL_HOOK="make MODE=xen  && make clean"
    - OCAML_VERSION=4.02 UPDATE_GCC_BINUTILS=1 POST_INSTALL_HOOK="make MODE=ukvm  && make clean"
    - OCAML_VERSION=4.02 UPDATE_GCC_BINUTILS=1 POST_INSTALL_HOOK="make MODE=virtio  && make clean"
