language: c
script: bash -ex .travis-ci.sh
env:
  - OCAML_VERSION=4.01.0 MIRAGE_BACKEND=unix OPAM_VERSION=1.0.0
  - OCAML_VERSION=4.00.1 MIRAGE_BACKEND=unix OPAM_VERSION=1.0.0
  - OCAML_VERSION=4.00.1 MIRAGE_BACKEND=xen  OPAM_VERSION=1.1.0
  - OCAML_VERSION=4.01.0 MIRAGE_BACKEND=xen  OPAM_VERSION=1.1.0
